sudo: false
language: ruby
rvm:
- 2.4.5
cache: bundler
script: bundle exec middleman build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: developer.grooveapp.com
  local-dir: build
  skip_cleanup: true
  region: us-west-2
  acl: public_read
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = "master"
